import '../components/app/layout';
import '../components/events/event'
import '../components/events/events';
import '../components/events/event-edit';
import '../components/events/event-head';
import '../components/events/order';
import '../components/pages/index';
import '../components/groups/group';
import '../components/groups/groups';
import '../components/groups/group-edit';
import '../components/items/items';
import '../components/items/item-cart';
import '../components/items/item-edit';
import  '../components/users/account';